### ISSUE TITLE
Error: A Serverless Function has exceeded the unzipped maximum size of 250 MB. : https://vercel.link/serverless-function-size

### ISSUE THREAD

**Issue by trevorpfiz** [cording12/next-fast-turbo#1]
First off, thank you for making this! It has been an amazing resource in helping me set up a FastAPI in a Monorepo with Next.js.

I am running into a maximum size issue when deploying the FastAPI. I have been referencing https://github.com/orgs/vercel/discussions/4354 to try to solve the problem.

Apparently, `builds` and `routes` are deprecated in `vercel.json`, so I am trying to convert that over with some trouble.

I will update when I know more!

![image](https://github.com/cording12/next-fast-turbo/assets/24904780/7e7f8b99-1dca-4cf0-a660-c5b80e4b8976)

**Comment by trevorpfiz** [comment]
```
{
  "rewrites": [{ "source": "/(.*)", "destination": "/api/main.py" }]
}
```

I tried to deploy it without `builds` in the monorepo, but it kept asking for an output directory. Then I tried to deploy it by itself following their the Vercel Django example, but got the same error as above. Maybe it is just too large and need to try to host somewhere else? Not sure.

**Comment by cording12** [comment]
Sorry for the delay; didn't realise my Github notifications were turned off.

Have you got an example repo you can share? Can't say I've run into this error and information on it seems relatively sparse.

One thing that could potentially be a factor is the Python version. When I built the repo in March, Vercel only supported Python 3.9, but according to [their docs](https://vercel.com/docs/functions/runtimes/python) it looks like they've moved up to Python 3.12 by default with 3.9 being legacy. 

I'll work on refactoring an updated version over the next week, but could be worth investigating.

**Comment by kenhuang1964** [comment]
Hey @cording12 , are you planning to release the updated version this week?

**Comment by trevorpfiz** [comment]
> ```
> {
>   "rewrites": [{ "source": "/(.*)", "destination": "/api/main.py" }]
> }
> ```
> 
> I tried to deploy it without `builds` in the monorepo, but it kept asking for an output directory. Then I tried to deploy it by itself following their the Vercel Django example, but got the same error as above. Maybe it is just too large and need to try to host somewhere else? Not sure.

I should add here that I used Docker to host this on Fly.io with no issues. Maybe just too large for Vercel serverless?

**Comment by cording12** [comment]
> Hey @cording12 , are you planning to release the updated version this week?

Afraid not this week - got a very busy week ahead but hoping to the week after.

**Comment by danielreuter** [comment]
This is incredibly useful @cording12 -- thanks for building. Just wondering what the status of the updated version is.
